### ISSUE TITLE
Refunding of payment intents throws Stripe::InvalidRequestError: No such charge: 

### ISSUE THREAD

**Issue by vortexkd** [stripe-ruby-mock/stripe-ruby-mock#822]
Trying to refund a payment intent like this

```
     payment_intent = Stripe::PaymentIntent.create(
        amount: 999,
        currency: 'USD'
      )

      refund = Stripe::Refund.create(
        payment_intent: payment_intent.id
      )
      expect(refund.amount).to eq(999)
```
as shown here
https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/master/spec/shared_stripe_examples/refund_examples.rb#L25

Yields the following error:
```
 Failure/Error:
       refund = Stripe::Refund.create(
         payment_intent: payment_intent.id
       )
     
     Stripe::InvalidRequestError:
       No such charge: 
     # /usr/local/bundle/gems/stripe-ruby-mock-3.1.0.rc3/lib/stripe_mock/instance.rb:182:in `assert_existence'
     # /usr/local/bundle/gems/stripe-ruby-mock-3.1.0.rc3/lib/stripe_mock/request_handlers/refunds.rb:21:in `new_refund'
     # /usr/local/bundle/gems/stripe-ruby-mock-3.1.0.rc3/lib/stripe_mock/instance.rb:129:in `mock_request'
     # /usr/local/bundle/gems/stripe-ruby-mock-3.1.0.rc3/lib/stripe_mock/api/instance.rb:10:in `block in start'
     # /usr/local/bundle/gems/stripe-5.44.0/lib/stripe/api_operations/request.rb:47:in `execute_resource_request_internal'
     # /usr/local/bundle/gems/stripe-5.44.0/lib/stripe/api_operations/request.rb:9:in `execute_resource_request'
     # /usr/local/bundle/gems/stripe-5.44.0/lib/stripe/api_operations/create.rb:7:in `create'
     # ./spec/requests/api/v1/xxx_spec.rb:240:in `block (4 levels) in <top (required)>'
```

I'm using stripe-ruby-mock-3.1.0.rc3 as you can see, but
lib/stripe_mock/request_handlers/refunds.rb:21
is 
```
charge = assert_existence :charge, params[:charge], charges[params[:charge]]
```
whereas in the repository the issue already seems to be fixed (as of 2 years ago) to check for payment intents
https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/3a14a8bd7e9e2e259fcc64987c852b4d8146d54c/lib/stripe_mock/request_handlers/refunds.rb#L22
```
if params[:payment_intent]
          payment_intent = assert_existence(
            :payment_intent,
            params[:payment_intent],
            payment_intents[params[:payment_intent]]
          )
```
Is there a newer release that has these changes that I can use in my gemfile?

I'm currently setting this:
```
gem 'stripe-ruby-mock', '~> 3.1.0.rc3', :require => 'stripe_mock'
```
